version: '3.3'
services:
  wordpress:
    container_name: wp-compose
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db-mysql
      - WORDPRESS_DB_USER=ismykiyo
      - WORDPRESS_DB_PASSWORD=ismykiyo
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
  mysql:
    container_name: db-mysql
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=ismykiyo
      - MYSQL_PASSWORD=ismykiyo
      - MYSQL_DATABASE=wordpress
    volumes:
      - database:/var/lib/mysql

  

volumes:
  database: {}